"Added pip install command to install dependencies, modified deployment validation to check HTTP status code and exit if not 200"

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -16,6 +16,7 @@ jobs:
       - name: Install dependencies
         run: |
           cd health-calculator-service
+          pip install -r requirements.txt
           make init
       - name: Run tests
         run: |
@@ -33,6 +34,11 @@ jobs:
           package: ./health-calculator-service
       - name: Validate deployment
         run: |
-          curl -s -o /dev/null -w "%{http_code}" curl -s -o /dev/null -w "%{http_code}" https://appwebdevops-c8aud5ddeygcgsge.francecentral-01.azurewebsites.net
+          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" https://appwebdevops-c8aud5ddeygcgsge.francecentral-01.azurewebsites.net)
+          if [ "$HTTP_CODE" -ne 200 ]; then
+            echo "Deployment failed with status code $HTTP_CODE"
+          exit 1
+          fi        
         env:
           EXPECTED_STATUS_CODE: 200
+#curl -s -o /dev/null -w "%{http_code}" curl -s -o /dev/null -w "%{http_code}" https://appwebdevops-c8aud5ddeygcgsge.francecentral-01.azurewebsites.net
